### ISSUE TITLE
How would this work with pagination?

### ISSUE THREAD

**Issue by bebraw** [christianalfoni/immutable-store#1]
I guess this is a more problem related to Flux in general but it probably doesn't hurt to think it through.

I have set up a paginating API (see [swagger-todo](https://github.com/bebraw/swagger-todo)). There are simple semantics for creating, manipulating and listing todos. In addition there is a simple way to generate a JavaScript API for it automatically (`/demo`). If needed I can implement more functionality (ie. get todos per indices).

From Store POV there are a couple of issues:

* How to deal with caching? Let's say you have a table of todos. The user will then navigate between pages. Instead of hitting the API always, you might want to display cached todos per page.
* What if a new item is added to some page? Now only a part of cache is correct. This should be taken in count somehow.
* How about other operations like searching? I guess this could go in phases. First you hit the backend with a query. The backend would then return indices and timestamps. You'll then do a diff against cache (checks ids + timestamps so you know which ones to update) and fetch missing items from backend.
* How about interactive syncing via WebSockets? If you have an environment where multiple people operate on the data, you might want to update the data continuously.

If you want, we can build something on top of `immutable-store` and `swagger-todo`. In case we get something nice together, perhaps it should go to the book as a full example.

**Comment by christianalfoni** [comment]
Hi @bebraw ,

These are absolutely valid concerns and challenges. I look at the **immutable-store** as a snapshot of your application state. The state that is needed to display the exact UI you are currently looking at now. In the DEMO you see it stores the state to localstorage, which means a refresh puts you right back where you were, even when editing a single todo. So that is the scope of the store. I should write more about that, thanks for pointing it out :-)

That said! I see caching and data storage as a separate layer. Something like this:

```javascript
var store = Store({
  todos: {
    list: [],
    isLoading: false,
    page: 1,
    itemsPrPage: 10
  }
});
var cache = {
  todos: [],
  loadTodos: function () {
    // Uses its own array with all todos
    // extracts from cache if valid by page/itemsprpage or
    // loads from API. Then adds them to the store, before
    // resolving promise with the store
  }
};

var actions = {
  loadTodos: function () {
    store = store.todos.set('isLoading', true);
    cache.loadTodos(store)
     .then(function (store) {
        store = store.todos.set('isLoading', false);
        events.emit('change' store);
      });
  },
  
};
```

Search would work the same way as loadTodos, only with a query of course. So when refreshing you will always get what you were looking at, but reverting the search/changing page would of course require a new download of todos, as the cache is cleared. But you could of course put the cache in localStorage too, if you wanted.

Syncing via websockets would also be a layer that points to both the actions and the cache. Since you might have two copies of the same todo. Something like:

```javascript
var websocket = {
  onTodo: function (todo) {
    cache.updateTodo(todo);
    actions.updateTodo(todo);
  }
};
```
If the todo did not exist, the cache would add it maybe and the actions would just ignore it.

Anyways, that are some initial thoughts :-)

Ah, yeah, this sounds like an awesome idea. Even just to research FLUX. If we could get an isomorphic todo app with cache and websocket together that would be awesome! I have to go through feedback stuff today, but can set up a repo tomorrow and make an inital commit? Then you can bring in swagger and we work from there?

**Comment by christianalfoni** [comment]
Or if we just work off swagger? Or maybe put swagger in new repo and continue from there... I dunno :-)

**Comment by bebraw** [comment]
The frontend can go to a separate repo. Easier to work that way. Feel free to set that up when you have time. I can develop the backend based on your needs (add queries, User model etc.).

Isomorphic rendering is something extra to think about.

**Comment by christianalfoni** [comment]
Too much to do at the moment, just cleaning up my inbox and the weight on
my shoulders ;-) It would be fun though!

lør. 21. feb. 2015 kl. 12.10 skrev Juho Vepsäläinen <
notifications@github.com>:

**Comment by bebraw** [comment]
Ok, no probs. :)
