### ISSUE TITLE
Deleting a key from an object

### ISSUE THREAD

**Issue by jrust** [christianalfoni/immutable-store#10]
I haven't found a great way to delete a key from an object.  The best I've come up with is:
```
store = Store({ items: { a: 1, b: 2 } });
store = store.set('items', _.omit(store.items.toJS(), 'a'));
```

It works, but it feels clunky because of the need for the `toJS()`.  Is there a better way?

**Comment by christianalfoni** [comment]
Great feedback, what about adding an `unset` method?

```js
store = Store({ items: { a: 1, b: 2 } });
store = store.unset('items', 'a'));
```

?

**Comment by jrust** [comment]
That sounds good.  I'll see if I can put up a PR here shortly.  I'm thinking of naming the method `delete` so that it can apply to an array element as well.  What do you think?

**Comment by christianalfoni** [comment]
Hmhm, I see that could be nice, but I think it differs a bit too much. Natively you have splice for removing items in arrays, which is more powerful as you can define how many and even add new items. So delete does not quite tell what it does with the array. Really want immutable-store to work just like native javascript :-)

Could of course use delete instead of unset, as that is what you do natively. Not sure about being a keyword though. `unset` is quite common, but could add both. `delete` if you do not care about keywords and `unset` as an alias :-)

But yeah, splice for array I think is important. Makes sense?

**Comment by jrust** [comment]
Great input on the API.  I agree, `unset` matches the `set` method nicely.
