### ISSUE TITLE
Improve performance of StoreArray

### ISSUE THREAD

**Issue by jrust** [christianalfoni/immutable-store#13]
Firefox shows this warning when using immutable-store:
```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
```

And it points to the prototype line on this piece of code:
```
  function StoreArray(items) {
    var inst = Array.apply(Array);
    inst = inst.concat(items);
    inst.__proto__ = StoreArray.prototype;
    return inst;
  }
```

I haven't actually verified it's claims, but it seems reasonable.

**Comment by christianalfoni** [comment]
Hi @jrust and thanks for pointing that out!

The problem is that this is the only way I know to make my own custom Array. When creating an object with the Array prototype it does not behave like an Array. 

Though the statement is most certainly right, I do not think it will affect immutable-store at an noticeable level. The reason is that it only runs this array stuff when instantiating the store and when you do some mutation on an array, or inside an array.

I believe you can subclass arrays in ES6 actually... so yeah, can optimize with that when it is ready :-)

**Comment by jrust** [comment]
Thanks for looking into it @christianalfoni -- I figured you had a better grasp of the internals than me :).  Gonna close since es6 is a little ways off.
